services: 
  postgres:
    image: postgres:12.4
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: dpa-user
      POSTGRES_PASSWORD: dpa-test
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dpa
      PGDATA: /data/db/data
    ports:
      - "5432:5432"
    volumes:
      - data:/data/db/data


  luigid:
    build: docker-images/luigid
    ports:
      - "8082:8082"
    volumes:
      - /usr/local/lib/python3.10/site-packages/luigi/static/visualiser
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: dpa-user
      POSTGRES_PASSWORD: dpa-test
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dpa
      LUIGI_TASK_HISTORY_DB_CONNECTION: postgres://dpa-user@postgres/dpa
      LUIGI_SCHEDULER_RECORD_TASK_HISTORY: "true"
    depends_on:
      - postgres


  luigi_worker:
    build: docker-images/luigi_worker
    links:
      - luigid:luigid
      - postgres:postgres
    environment:
      LUIGI_CORE_DEFAULT-SCHEDULER-URL: http://scheduler:8082
      LC_ALL: C.UTF-8
      POSTGRES_USER: dpa-user
      POSTGRES_PASSWORD: dpa-test
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dpa
      PGDATA: /data/db/data
    #command: make deploy
    volumes:
      - coop-audio:/datalake

volumes:
   data:
     driver: local # Define the driver and options under the volume name
     driver_opts:
       type: none
       device: /home/jose_antonio_ramirez/data
       o: bind
   coop-audio:
     driver: ofekmeister/gcsfs
     driver_opts:
       key: verdant-branch-401919-f616c4765daf.json


